### ISSUE TITLE
Resume playback not working.

### ISSUE THREAD

**Issue by bennodxb** [croneter/PlexKodiConnect#1017]
Hi, I am having a problem with resume. It doesn't work ever, all shows and movies start from the beginning even though I choose "resume from XX:xx" Files saved on local HDD and played directly resume correctly. I also have a less common issue where kodi seems to lock up when i exit playback. This issue occurred again when I ran the test of resume to produce the following log.
I have not experienced either of these issues prior t using PKC. 
Thanks.

https://pastebin.com/4wzLgDhx

**Comment by croneter** [comment]
Did the resume pop-up appear when you captured the this log file?

**Comment by bennodxb** [comment]
I honestly cant remember, Im leaning towards no. I think if i resume from widget theres no popup. I think the popup only comes if i go through library. This particular log was using Titan Bingie skin which has a resume or play from beginning option built into the info page. I tried using estuary only and the resume still didnt work. Shall i make a log like that instead?

**Comment by croneter** [comment]
Please switch to the Kodi standard skin Estuary. Make sure Kodi debug logging is enabled. Then reset the Kodi database in the PKC settings under Advanced, hitting Yes, then No. Reboot Kodi and let pkc resync. Then immediately try to play a movie that has been partially watched, trying to resume from where you left off. Then immediately share the Kodi log file - I can thus see both the sync process as well as you trying to resume

**Comment by croneter** [comment]
Possible solution from https://www.reddit.com/r/PleX/comments/dh4xtq/which_if_any_clients_have_full_ass_subtitle/

> When I looked at the PKC code, I saw the only way it supports resume is through the resume dialog that it pops up. However, many skins including Bingie don't use this dialog. But, Kodi sends a resume parameter to sys.argv when it calls the plugin on play. In sys.argv in plexkodiconnect.tvshows or movies, there is a "resume:true" (or "resume:false") parameter passed that PKC is ignoring. Kodi sets this parameter to true when playback should be resumed (it can explicitly be set by the skin with a PlayMedia(..., resume) or PlayMedia(..., noresume) call, but it's also set implicitly by Kodi like if you select resume as the default video select action in settings). You can see the parameter passed last in the log:

```2019-10-13 15:15:53.680 T:20392   DEBUG: PLEX.TVSHOWS: Full sys.sys.argv received: ['plugin://plugin.video.plexkodiconnect.tvshows/499006/', '30', '?plex_id=499143&plex_type=episode&mode=play&filename=Dragon Ball - S02E07 - Elimination Round.mkv', 'resume:true']```
So basically, I handled the resume:true parameter in play() in plexkodiconnect.tvshows and propagated it to the plexkodiconnect plugin where it got handled in playback_starter.py and then playback.py. Then I added it to the resume logic in playback.py for all types of content. Also, the plugin gets called twice sometimes so I had to tack on an extra parameter to the second call URL so it knows resume is set the second time around. Now all the resume functionality works whether it's from the skin's resume button or from the context menu or from the default select action.

> Here's a diff with the changed files. You can see how I did it exactly, but I don't know the PKC code that well, so I didn't really do an optimal job. Just a quick hack that worked. I'm sure you can figure out a better way to propagate the variables and make it fit in better with your logic.

> Other than resume, there weren't any other problems that were PKC's fault. One other issue was that every time I was navigating back to the home screen on Bingie which had a widget with PKC plugin videos in it, PKC would suddenly play the video file that was highlighted without me clicking on it. I traced this back in the Kodi source code to CDirectoryProvider::UpdateURL() getting called when the widget refreshes, which ends up trying to directory refresh the widget's currently focused video's plugin URL, which activates that PKC video. I ended up adding an if statement in the Kodi source code in UpdateURL to ignore URLs that match the regex "plugin://plugin.video.plexkodiconnect.*mode=play". Not a very good solution because now I have to recompile Kodi for my Shield whenever an update comes out, but nothing else worked and I couldn't figure out a way from the skin to change this functionality.

> There were some other issues with some of the buttons in the Bingie skin using PlayMedia(videodb://tvshows/$INFO[ListItem.DBID]) which didn't work when the tv show URL is a plugin, so I had to change them to use PlayMedia(...ListItem.FullNameAndPath) instead which contained the plugin URL which PlayMedia supports. Then there was a bug in Kodi that didn't always set FullNameAndPath correctly for certain widget items with plugin paths instead of "video://" paths so I changed the Kodi source at CVideoInfoGUI:::GetLabel to better handle plugin URLs.

**Comment by croneter** [comment]
```
diff -urw PlexKodiConnect/plugin.video.plexkodiconnect/resources/lib/playback.py PlexKodiConnect.with-resume/plugin.video.plexkodiconnect/resources/lib/playback.py
--- PlexKodiConnect/plugin.video.plexkodiconnect/resources/lib/playback.py	2019-10-14 11:51:03.355830191 -0600
+++ PlexKodiConnect.with-resume/plugin.video.plexkodiconnect/resources/lib/playback.py	2019-10-08 01:37:18.723636085 -0600
@@ -30,7 +30,7 @@
 ###############################################################################


-def playback_triage(plex_id=None, plex_type=None, path=None, resolve=True):
+def playback_triage(plex_id=None, plex_type=None, path=None, resolve=True, resume=False):
     """
     Hit this function for addon path playback, Plex trailers, etc.
     Will setup playback first, then on second call complete playback.
@@ -46,8 +46,12 @@
     the first pass - e.g. if you're calling this function from the original
     service.py Python instance
     """
+    if resume == '1':
+        resume = True
+    elif resume is not None:
+        resume = False
     try:
-        _playback_triage(plex_id, plex_type, path, resolve)
+        _playback_triage(plex_id, plex_type, path, resolve, resume)
     finally:
         # Reset some playback variables the user potentially set to init
         # playback
@@ -56,7 +60,7 @@
         app.PLAYSTATE.resume_playback = None


-def _playback_triage(plex_id, plex_type, path, resolve):
+def _playback_triage(plex_id, plex_type, path, resolve, resume):
     plex_id = utils.cast(int, plex_id)
     LOG.info('playback_triage called with plex_id %s, plex_type %s, path %s, '
              'resolve %s', plex_id, plex_type, path, resolve)
@@ -113,7 +117,7 @@
             if ('id' not in item and
                     item.get('type') == 'unknown' and item.get('title') == ''):
                 LOG.info('Kodi playlist play detected')
-                _playlist_playback(plex_id, plex_type)
+                _playlist_playback(plex_id, plex_type, resume)
                 return

         # Can return -1 (as in "no playlist")
@@ -136,13 +140,13 @@
             LOG.debug('Detected re-playing of the same item')
             initiate = True
         if initiate:
-            _playback_init(plex_id, plex_type, playqueue, pos)
+            _playback_init(plex_id, plex_type, playqueue, pos, resume)
         else:
             # kick off playback on second pass
-            _conclude_playback(playqueue, pos)
+            _conclude_playback(playqueue, pos, resume)


-def _playlist_playback(plex_id, plex_type):
+def _playlist_playback(plex_id, plex_type, resume=None):
     """
     Really annoying Kodi behavior: Kodi will throw the ENTIRE playlist some-
     where, causing Playlist.onAdd to fire for each item like this:
@@ -172,10 +176,10 @@
     playqueue.kodi_playlist_playback = True
     playlist_item = PL.playlist_item_from_xml(xml[0])
     playqueue.items.append(playlist_item)
-    _conclude_playback(playqueue, pos=0)
+    _conclude_playback(playqueue, pos=0, resume=resume)


-def _playback_init(plex_id, plex_type, playqueue, pos):
+def _playback_init(plex_id, plex_type, playqueue, pos, force_resume):
     """
     Playback setup if Kodi starts playing an item for the first time.
     """
@@ -204,7 +208,7 @@
             return
         # Now we need to use setResolvedUrl for the item at position ZERO
         # playqueue.py will pick up the missing items
-        _conclude_playback(playqueue, 0)
+        _conclude_playback(playqueue, 0, force_resume)
         return
     # "Usual" case - consider trailers and parts and build both Kodi and Plex
     # playqueues
@@ -222,7 +226,7 @@
     elif app.SYNC.direct_paths:
         resume = False
     else:
-        resume = app.PLAYSTATE.resume_playback or False
+        resume = force_resume or app.PLAYSTATE.resume_playback or False
     trailers = False
     if (not resume and plex_type == v.PLEX_TYPE_MOVIE and
             utils.settings('enableCinema') == "true"):
@@ -361,6 +365,8 @@
                 #                     'plugin.video.plexkodiconnect', 1)
                 # path = path.replace('plugin.video.plexkodiconnect.movies',
                 #                     'plugin.video.plexkodiconnect', 1)
+                if i + 1 == len(xml) and part == 0 and resume:
+                    path += "&resume=1"
                 listitem = api.listitem()
                 listitem.setPath(path.encode('utf-8'))
             else:
@@ -413,10 +419,11 @@
         pos += 1


-def _set_resume(listitem, item, api):
+def _set_resume(listitem, item, api, resume=None):
     if item.plex_type in (v.PLEX_TYPE_SONG, v.PLEX_TYPE_CLIP):
         return
-    if item.resume is True:
+    force_resume = resume if resume is not None else item.resume
+    if force_resume is True:
         # Do NOT use item.offset directly but get it from the DB
         # (user might have initiated same video twice)
         with PlexDB(lock=False) as plexdb:
@@ -442,7 +449,7 @@
         listitem.setProperty('StartPercent', '0')


-def _conclude_playback(playqueue, pos):
+def _conclude_playback(playqueue, pos, resume=None):
     """
     ONLY if actually being played (e.g. at 5th position of a playqueue).

@@ -478,7 +485,7 @@
     elif item.playmethod in (v.PLAYBACK_METHOD_DIRECT_STREAM,
                              v.PLAYBACK_METHOD_TRANSCODE):
         audio_subtitle_prefs(api, listitem)
-    _set_resume(listitem, item, api)
+    _set_resume(listitem, item, api, resume)
     transfer.send(listitem)
     LOG.info('Done concluding playback')

diff -urw PlexKodiConnect/plugin.video.plexkodiconnect/resources/lib/playback_starter.py PlexKodiConnect.with-resume/plugin.video.plexkodiconnect/resources/lib/playback_starter.py
--- PlexKodiConnect/plugin.video.plexkodiconnect/resources/lib/playback_starter.py	2019-10-14 11:51:03.356830212 -0600
+++ PlexKodiConnect.with-resume/plugin.video.plexkodiconnect/resources/lib/playback_starter.py	2019-10-08 01:37:18.723636085 -0600
@@ -40,7 +40,8 @@
             playback.playback_triage(plex_id=params.get('plex_id'),
                                      plex_type=params.get('plex_type'),
                                      path=params.get('path'),
-                                     resolve=resolve)
+                                     resolve=resolve,
+                                     resume=params.get('resume'))
         elif mode == 'plex_node':
             playback.process_indirect(params['key'],
                                       params['offset'],
diff -urw PlexKodiConnect/plugin.video.plexkodiconnect.movies/default.py PlexKodiConnect.with-resume/plugin.video.plexkodiconnect.movies/default.py
--- PlexKodiConnect/plugin.video.plexkodiconnect.movies/default.py	2019-10-14 11:50:00.996521831 -0600
+++ PlexKodiConnect.with-resume/plugin.video.plexkodiconnect.movies/default.py	2019-10-14 11:47:22.023117440 -0600
@@ -35,6 +35,8 @@
     """
     LOG.debug('Full sys.argv received: %s', sys.argv)
     request = '%s&handle=%s' % (unicode_paths.decode(sys.argv[2]), HANDLE)
+    if "resume:true" in sys.argv:
+        request += "&resume=1"
     # Put the request into the 'queue'
     transfer.plex_command('PLAY-%s' % request)
     if HANDLE == -1:
diff -urw PlexKodiConnect/plugin.video.plexkodiconnect.tvshows/default.py PlexKodiConnect.with-resume/plugin.video.plexkodiconnect.tvshows/default.py
--- PlexKodiConnect/plugin.video.plexkodiconnect.tvshows/default.py	2019-10-14 11:50:13.295780957 -0600
+++ PlexKodiConnect.with-resume/plugin.video.plexkodiconnect.tvshows/default.py	2019-10-14 11:46:18.243718102 -0600
@@ -42,6 +42,8 @@
         return
     else:
         request = '%s&handle=%s' % (unicode_paths.decode(sys.argv[2]), HANDLE)
+        if "resume:true" in sys.argv:
+            request += "&resume=1"
         transfer.plex_command('PLAY-%s' % request)
     if HANDLE == -1:
         # Handle -1 received, not waiting for main thread
```

**Comment by bennodxb** [comment]
Sorry, I haven't had time to reset everything as requested. 
Should I put this last section somewhere?

**Comment by croneter** [comment]
No, that's too complicated. I'll let you know when and what to test. I think I can fix this issue now

**Comment by bennodxb** [comment]
Hey, how goes it? Not working out as expected? Should I do the reset after all? 
Thanks

**Comment by Peinuzumaki** [comment]
> No, that's too complicated. I'll let you know when and what to test. I think I can fix this issue now

So what is the update on this exactly? Can the end user easily fix this or is this going to be addressed within the next update?

**Comment by thomfam** [comment]
Having the same problem.  I am not using the Estuary skin, I am using Xonfluence skin as it is highly customisable and it does exactly as I want it to do.  Looking forward to an update to remedy this hassle.

**Comment by peacey** [comment]
If you guys really need this fixed before croneter finds time to debug and fix it properly, you can patch PlexKodiConnect with my temporary solution that croneter sourced 6 posts ago. I've uploaded the patch file at the end of this post. Download the patch file and exit Kodi, open a terminal, and go to the Kodi addon folder in the terminal (different location for each OS, on my Shield it's at /sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons), and type in the terminal:

`patch -p1 -i /path/to/pkc_resume_patch.txt`

It should patch 4 files without errors if you're on the latest PKC beta 2.9.11. Then open Kodi and resume should be working. 

Note I can't guarantee nothing will break with this patch. I haven't encountered any issues myself, but if you do encounter any issues you can just revert back by re-downloading/re-updating the PlexKodiConnect add-ons in Kodi. 

Patch file: [pkc_resume_patch.txt](https://github.com/croneter/PlexKodiConnect/files/3770417/pkc_resume_patch.txt)

**Comment by thomfam** [comment]
Thanks peacy but as my avatar shows though I enjoy my PC, a programming expert I am not.  I too have Shield which I I can access from my PC.  But when you said 'open a terminal' was that on my PC or the Shield? To top it all off I have no idea how to open a terminal in Android.  I am will to have a go but maybe there is a youtube video I could check out on this.  Either that or I will have to wait for the update.

**Comment by bennodxb** [comment]
Thanks, I too am running kodi on the shield. I would also give it a try if its possible on android.Could you just upload the 4 files? or it doesnt work like that.

**Comment by bennodxb** [comment]
The updated version works perfectly thanks. Resume is back.

**Comment by croneter** [comment]
Try PKC beta version 2.9.12 - should work now

**Comment by peacey** [comment]
croneter, it seems you forgot to merge the `offset = offset or 0; if offset >= 0` suggestion, because I don't see it in the final changes and "Play from beginning" is broken now with 2.9.12 due to "if offset:" not evaluating to True when offset is 0 or None.

**Comment by croneter** [comment]
Darn, a rebase fault of mine

**Comment by croneter** [comment]
OK, should be fixed. Working now with PKC beta version 2.9.13?

**Comment by peacey** [comment]
Thanks croneter! It's all working now on both the Estuary and Bingie skins.
