### ISSUE TITLE
Plex DVR Beta 3 Crash

### ISSUE THREAD

**Issue by riffy13** [croneter/PlexKodiConnect#123]
It constantly crashes/disconnects or whatever it's doing, with the DVR Beta 3. Unstable to the point of unusable. 
[KodiDisconect.zip](https://github.com/croneter/PlexKodiConnect/files/518614/KodiDisconect.zip)

**Comment by riffy13** [comment]
Here's a 2fer! It duplicated Avatar & crashed. weeeeee.... :-)
[Kodi2fer.zip](https://github.com/croneter/PlexKodiConnect/files/518621/Kodi2fer.zip)

**Comment by croneter** [comment]
Should be fixed with the new BETA PKC version. Do report back ;-)

**Comment by riffy13** [comment]
Reinstalling Beta 3 & installing your beta 1.3.9! 
*crosses fingers*

**Comment by riffy13** [comment]
After it rebuilt the database, I reset everything but the settings in the addon, I still get the unstable message pop up.
[KodiUnstableBetas.zip](https://github.com/croneter/PlexKodiConnect/files/522567/KodiUnstableBetas.zip)

**Comment by riffy13** [comment]
Yeah... still not working. Noticed it did lose the connection cuz nothing ever updated after that message.

**Comment by croneter** [comment]
Dude, install the BETA PlexKodiConnect repository and use PKC version 1.3.9. You are still on 1.3.3 ;-). 

No need to reinstall anything. Just additionally add the beta repository

**Comment by riffy13** [comment]
I just checked. It is on 1.3.9. I have both repositories installed but the add on version is 1.3.9. I had to rebuild the database anyways cuz I had dozens of duplicate movies. I rolled back to Beta 2 tho after 3-4 restarts.

**Comment by riffy13** [comment]
AHH! That's the wrong log! LOL Downloaded it from here & that's some how not the right log. I reinstalled beta 3 & will upload another log after it crashes again. Not sure how the hell I did that. :-p

**Comment by riffy13** [comment]
OK I have no idea what happened or how I did it or if there's gremlins in my Kodi puter or what but... after I looked again at the time stamps, that was the right log. I did update to 1.3.9 in the addons I swear! Even reset the database. I even restarted Kodi a number of times. They all show 1.3.3 in the logs. BUT... After the computer was rebooted it now shows as 1.3.9 in the logs & hasn't crashed once on beta 3. So maybe it is fixed. 

It was driving me crazy trying to figure out how I uploaded the wrong logs. Personally I blame gluten! Or Obama. Maybe aliens. One of them!

**Comment by riffy13** [comment]
It did eventually crash. Ran for quite awhile tho without issues. Here is the log. 
[KodiLog.zip](https://github.com/croneter/PlexKodiConnect/files/525765/KodiLog.zip)

**Comment by croneter** [comment]
Thanks for the last log! Was a crash that was completely unrelated, but yet unknown to me :-)

**Comment by riffy13** [comment]
Cool! That crash happens quite a bit. Like every few hours.

**Comment by croneter** [comment]
Update your PKC to 1.4.0,its fixed now

**Comment by riffy13** [comment]
It did update itself this morning. Snuck that fix in too? :-o Cool!!
