### ISSUE TITLE
Error function missing when try to delete

### ISSUE THREAD

**Issue by BartOon** [croneter/PlexKodiConnect#1351]
## Help yourself
* I did try to restart Kodi :-) >> Lmao, I reboot the computer too
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq) >> I hope I checked well
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO >> I did, and to be sure I restarted Kodi setup, (remove roaming folder and start over)
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues) >> I didn't see something related to my issue

## Describe the bug
Error message with red cross when try to delete anything from Plex Server.
Message is "PlexKodiConnect, function missing required argument 'message' (pos 2)"
![PKC-deletion error message](https://user-images.githubusercontent.com/3241239/108612662-c7e85180-73b8-11eb-8800-9a51f3192584.PNG)

## To Reproduce
After basic setup, Addon (Default) for path, no Plex Music, no additional fanart.
I enable Allow file renaming and deletion, in Settings, Media, General, restart Kodi to make available the Delete item from server option
1. Right click in any item, video for me
2. Click on Plex options
3. Click on Delete item from server

## Expected behavior
Suppose to remove the item from the list, with an confirmation message and delete it in the server.

## You need to attach a KODI LOG FILE!
see attachment
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/6016932/kodi.log)

**Comment by croneter** [comment]
Thanks for the detailed report! Should be fixed with PKC version 3.0.11

**Comment by BartOon** [comment]
Is it fixed ?
When I reported the issue I did a brand new Kodi and PKC setup, but I recovered back a previous configuration whom still have the issue, don't know if my configuration is corrupted or not, I'm in version 3.0.12 Matrix release,

**Comment by BartOon** [comment]
Same thing with version 3.0.13 with Matrix stable repo

**Comment by croneter** [comment]
Kindly share a DEBUG log file as before, @BartOon

**Comment by BartOon** [comment]
Here is, hope that's help.
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/6055737/kodi.log)

**Comment by croneter** [comment]
Should be fixed in beta version 3.0.14!

**Comment by BartOon** [comment]
It’s fixed !
thx

**Comment by MrRobot12** [comment]
I have this same issue. Typically how long does it take for beta to make it into stable? Or should I just upgrade to the beta now?
