### ISSUE TITLE
UPDATE movie itemid loop with latest updates?

### ISSUE THREAD

**Issue by troych** [croneter/PlexKodiConnect#194]
Hi there, I'm not sure if this is supposed to work like this but I seem to have a consistent update loop of all my movies since the last couple of beta versions.

Befoe I took those logs I did a complete reset of my database including cached artwork. As you can see with the example of Pulp Fiction here, it adds all the movies and then keeps updating them forever in a loop. This goes on until I manually turn off the HTPC.

On the Plex server side I can also see that processes all these movies all the time and only stops when I turn off PKC.

Any idea what may cause this?

I'm on:
Kodi 17.0-BETA7 Git:2017-01-01-5b144f5
Plex: 1.3.3.3148
PKC 1.5.8

cat /home/kodi/.kodi/temp/kodi.log | grep Pulp
```
14:28:02.439 T:140696332752640  NOTICE: PLEX.itemtypes -> ADD movie itemid: 998 - Title: Pulp Fiction
14:32:39.330 T:140696569960192  NOTICE: PLEX.itemtypes -> UPDATE movie itemid: 998 - Title: Pulp Fiction
14:35:59.993 T:140696569960192  NOTICE: PLEX.itemtypes -> UPDATE movie itemid: 998 - Title: Pulp Fiction
14:40:22.651 T:140696569960192  NOTICE: PLEX.itemtypes -> UPDATE movie itemid: 998 - Title: Pulp Fiction
14:44:11.631 T:140696569960192  NOTICE: PLEX.itemtypes -> UPDATE movie itemid: 998 - Title: Pulp Fiction
14:47:40.224 T:140696569960192  NOTICE: PLEX.itemtypes -> UPDATE movie itemid: 998 - Title: Pulp Fiction
14:49:56.196 T:140696569960192  NOTICE: PLEX.itemtypes -> UPDATE movie itemid: 998 - Title: Pulp Fiction
14:52:41.061 T:140696569960192  NOTICE: PLEX.itemtypes -> UPDATE movie itemid: 998 - Title: Pulp Fiction
14:54:46.690 T:140696569960192  NOTICE: PLEX.itemtypes -> UPDATE movie itemid: 998 - Title: Pulp Fiction
14:56:51.373 T:140696569960192  NOTICE: PLEX.itemtypes -> UPDATE movie itemid: 998 - Title: Pulp Fiction
14:58:56.092 T:140696569960192  NOTICE: PLEX.itemtypes -> UPDATE movie itemid: 998 - Title: Pulp Fiction
15:01:05.630 T:140696569960192  NOTICE: PLEX.itemtypes -> UPDATE movie itemid: 998 - Title: Pulp Fiction
15:03:09.670 T:140696569960192  NOTICE: PLEX.itemtypes -> UPDATE movie itemid: 998 - Title: Pulp Fiction
....
19:22:45.163 T:140696569960192  NOTICE: PLEX.itemtypes -> UPDATE movie itemid: 998 - Title: Pulp Fiction
```

**Comment by croneter** [comment]
Weird issue... Can you please enable **PlexKodiConnect** debugging in the PKC settings under Advanced? Then try to catch the issue again

**Comment by troych** [comment]
Done, I also noticed I get a python error right before the first connection succeeded message from PKC.

```
08:13:13.147 T:140288152545024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: Service instance has no attribute 'image_cache_thread'
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 353, in <module>
                                                Service().ServiceEntryPoint()
                                              File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 220, in ServiceEntryPoint
                                                self.image_cache_thread.start()
                                            AttributeError: Service instance has no attribute 'image_cache_thread'
                                            -->End of Python script error report<--
08:13:13.147 T:140288152545024    INFO: CPythonInvoker(10, /home/kodi/.kodi/addons/plugin.video.plexkodiconnect/service.py): waiting on thread 140287530546944
```

And complete log with PKC in debug mode (reset database again): [kodi.zip](https://github.com/croneter/PlexKodiConnect/files/744099/kodi.zip)

**Comment by croneter** [comment]
Thanks. What version of Plex Media Server are you running?

**Comment by croneter** [comment]
Does the issue persist if you **enable** image caching in the PKC settings under Artwork?

**Comment by troych** [comment]
Plexserver: 1.3.3.3148 (latest version according to the updater)

Looks like the initial python error is gone with enabled image caching, not sure why I turned it off in the first place. It finished syncing and is caching art now, looking good.

**Comment by troych** [comment]
I'm pretty sure it's still in the same update loop, getting a lot more infos with the debug setting so it's hard to tell by eye but I see it caching the same fanart over and over again if I grep for the URL of a particular one.

[kodi.zip](https://github.com/croneter/PlexKodiConnect/files/744377/kodi.zip)

**Comment by croneter** [comment]
Pretty weird stuff going on here. After an update on the PKC side, it takes 2-3 minutes to start again. Seems triggered on the PMS side, not PKC. What are your PMS settings in the tab `Library`? Mine are below; no issues on a Windows PMS whatsoever

![unbenannt](https://cloud.githubusercontent.com/assets/4637940/22502302/a6588d0e-e86c-11e6-92d4-becf7d07d5a7.PNG)

**Comment by croneter** [comment]
Try this:
* Exit PKC/Kodi
* Use your browser to access your PMS
* Go to the affected library, e.g. where the movie `The Thirteenth Floor` is located
* Hit the wheel thingy at the top right to trigger `Update library`. Let it finish
* Try again with PKC and see if it helps with `The Thirteenth Floor`

Also, could you share a PMS log with debugging enabled on the PMS side? While these loops are going on, of course ;-)

**Comment by troych** [comment]
I think I see where things went wrong, I always only checked on the Kodi/PKC side since PMS seemed to be running just fine but it looks like PMS was lacking some file permissions for my media folders. It was trying to analyse files and couldn't because of this. I guess thats what triggered the update spiral.

Since I've fixed the permissions I don't get the  "Finished processing" entry for every movie any more in the PMS logs and no "UPDATE movie itemid" in my kodi log. I'll report back, but I think thats solved now.

Thanks for the help already, I'll close this once I see everything has properly finished. :)

**Comment by croneter** [comment]
Cool, thanks for reporting back!
