### ISSUE TITLE
Omega beta 3

### ISSUE THREAD

**Issue by Romik2505** [croneter/PlexKodiConnect#2025]
In Omega beta 3, movies are also not displayed. TV shows, on the other hand, work.

**Comment by hyenaHD** [comment]
Same issue here...

**Comment by AvAars** [comment]
As discussed here: https://github.com/jellyfin/jellyfin-kodi/issues/808
Kodi made some DB changes (supposedly to support multiple versions of a movie) and that broke these kind of addons.
The diff of the database is also mentioned there

**Comment by bokkoman** [comment]
Also reported here, on a closed ticket.

https://github.com/croneter/PlexKodiConnect/issues/1988#issuecomment-1949374663

**Comment by Abasz** [comment]
> TV shows, on the other hand, work.

For me new episodes of series did not sync, but only already synced episodes were playable. I downgraded back to beta2 (by uninstalling and side loading apk) now everything is working.

Interesting choice to introduce a breaking change to database schema during beta  :)

**Comment by bokkoman** [comment]
> > TV shows, on the other hand, work.
> 
> For me new episodes of series did not sync, but only already synced episodes were playable. I downgraded back to beta2 (by uninstalling and side loading apk) now everything is working.
> 
> Interesting choice to introduce a breaking change to database schema during beta :)

Why? Its called beta for a reason.
Kodi can do whatever they want, they are not dependent on the add-ons 😉

**Comment by croneter** [comment]
Fixed in PKC Beta version 3.8.5

**Comment by aaronmmarks** [comment]
I'm still having this issue with Kodi 21 Beta 3 and PKC Beta 3.8.6. Is that expected/known?

**Comment by bokkoman** [comment]
> I'm still having this issue with Kodi 21 Beta 3 and PKC Beta 3.8.6. Is that expected/known?

Works for me. Did you reset the DB?

**Comment by croneter** [comment]
Latest PKC version is 3.8.8, use that one!
