### ISSUE TITLE
Wrong resolution when transcoding

### ISSUE THREAD

**Issue by SuperPepperoni** [croneter/PlexKodiConnect#2122]
* I did try to restart Kodi
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describing the bug
Somehow, whenever I try to transcode a video, it ends up as a 720x404 even though the expected behaviour is for it to transcode into a 1080p/8Mbps. I saw someone [with a similar issue](https://github.com/croneter/PlexKodiConnect/issues/1864) but they didn't post their log, and thus never got their reply.

## To reproduce
To reproduce the error, just simply start any video (from any library) with a bitrate that goes over the set limit (Mine is set it as 12MB).

## Expected behaviour
The expected behaviour is for the video transcode into a 1080p/8Mbps.

## Log
https://pastebin.com/R42zSgxJ

**Comment by croneter** [comment]
Thanks for your bug-report. PlexKodiConnect decides that this URL should be used to play the video, which explicitly tells the PMS `videoResolution=1920x1080`
```
info <general>: PLEX.playback_decision: The playurl for Transcode is: https://plex.asiaflix.fr:443/video/:/transcode/universal/start.m3u8?Accept=%2A%2F%2A&Content-Type=application%2Fx-www-form-urlencoded&Accept-Language=en&X-Plex-Device=Windows&X-Plex-Model=10&X-Plex-Device-Name=Kodi+DESKTOP-1TUGG18&X-Plex-Platform=Generic&X-Plex-Platform-Version=1.0.0&X-Plex-Product=PlexKodiConnect&X-Plex-Version=3.10.4&X-Plex-Client-Identifier=d9dcb950-fd09-4274-a3b9-c3e4f302d3ae&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Protocol=1.0&Cache-Control=no-cache&X-Plex-Token=[TOKEN]&path=%2Flibrary%2Fmetadata%2F968887&directPlay=0&directStream=0&directStreamAudio=0&hasMDE=0&mediaIndex=0&partIndex=0&audioBoost=0&autoAdjustQuality=0&protocol=hls&session=d9dcb950-fd09-4274-a3b9-c3e4f302d3ae&fastSeek=1&copyts=1&maxVideoBitrate=3000&videoResolution=1920x1080&videoQuality=100&mediaBufferSize=20480&subtitleSize=100
```

**Comment by SuperPepperoni** [comment]
I see... so you would say it's a Plex side issue? Do you want me to try a different setting, etc? Or maybe just wait for a possible fix?

**Comment by croneter** [comment]
It's not a Plex issue, but I think at some point the Plex API changed. I'm testing with a Plex Android client now, and what's going back and forth between the PMS and the client does NOT tell me anything about the resolution, unfortunately. The resolution thus might be the result of some decision process on the PMS side that we can't really influence except indirectly e.g. with max video bit rate.

**Comment by croneter** [comment]
Current state: PKC thinks that passing `videoResolution` sets the target resolution. But looking at Plex Android clients, `videoResolution` is always e.g. `videoResolution=3840x2160` and seems to only reflect the original videos resolution, no matter whether I choose to transcode to 1080p or 720p.

**Comment by croneter** [comment]
Seems like the resolution is "hard-coded" to the bit rate. When looking at Android clients:
```
20 Mbps - 1080p High Quality
12 Mbps - 1080p Middle Quality
8 Mbps - 1080p
4 Mbps - 720p High Quality
3 Mbps - 720p Middle Quality
2 Mbps - 720p
1.5 Mbps - 480p
0.7 Mbps - 320p
0.3 Mbps - 240p
```

Could you please check with your official Plex clients whether you see some other combo, @SuperPepperoni ?

**Comment by SuperPepperoni** [comment]
Nope, it's pretty much the same except for the last one (160p, 0.2mbps).
Same goes on my Android app and the Chromecast app, just to make sure.

![image](https://github.com/user-attachments/assets/ada62c08-e505-45b0-89e4-e4bc8416e983)

**Comment by croneter** [comment]
Hopefully fixed with PKC beta version 3.10.5

**Comment by SuperPepperoni** [comment]
on god, idk how to say this but-- it's still not working for me 😭😭 and yes, i updated it to 3.10.5. i'm so sorry... it's still forcing the video to 720x404. don't know if i should do a full reset of all my settings again or?

edit: i originally wrote this comment on the #2124 pull, before noticing i did it at the wrong comment box

**Comment by SuperPepperoni** [comment]
Here's a new log, with the beta version: https://pastebin.com/ws69nE9G
hope this helps.

**Comment by croneter** [comment]
No worries. Try choosing another transcoding quality in the PKC settings. Try to play something. What do the PMS logs tell you about transcoding if you enable PMS debug logging?

**Comment by SuperPepperoni** [comment]
* Try choosing another transcoding quality in the PKC settings
I did, tried 720p/4Mbps. Sadly, nothing changed. Also tried with different videos from my library, different codecs, etc... Still.

*  What do the PMS logs tell you about transcoding if you enable PMS debug logging?
Here it is: [the PMS Debug Log](https://gist.github.com/SuperPepperoni/05f16254375112fe777544770401f3a9) (Tested by transcoding it to 720p/4Mbps)

**Comment by croneter** [comment]
I'm struggling with your PMS logs. I get mine by just going to the PMS settings, Troubleshooting, "Download logs", then pick the "Plex Media Server.log" file after just having started a PKC transcoding session. The most informative lines look like this:
```
# Info how PKC's request looked like
DEBUG - Request: [10.244.3.27:50000 (WAN)] GET /video/:/transcode/universal/decision?path=%2Flibrary%2Fmetadata%2F875409&directPlay=0&directStream=0&directStreamAudio=0&hasMDE=0&mediaIndex=0&partIndex=0&audioBoost=0&autoAdjustQuality=0&protocol=hls&session=a11cde42-ba28-4fdc-9bdc-7ee9f08416c2&fastSeek=1&copyts=1&videoBitrate=10000&maxVideoBitrate=10000&videoResolution=1920x1080&videoQuality=100&mediaBufferSize=20480&subtitleSize=100 (12 live) #b0c67 TLS Signed-in Token (croneter) (Kodi)
...
# info if the PMS overruled the transcoding settings PKC asked for
...
# info how the transcoded video stream will actually look like
DEBUG - [Req#b0c67/Transcode] Streaming Resource: Reached Decision id=875409 codes=(General=1001,Direct play not available; Conversion OK. Direct Play=3000,App cannot direct play this item. Direct play is disabled. Transcode=1001,Direct play not available; Conversion OK.) media=(id=2124625 part=(id=2147925 decision=transcode container=mpegts protocol=hls streams=(Video=(id=4436223 decision=transcode bitrate=9006 encoder=h264_vaapi width=1920 height=1080) Audio=(id=4436225 decision=transcode bitrate=381 encoder=libopus channels=6 rate=48000))))
```

**Comment by SuperPepperoni** [comment]
Oop, but that's assuming I own the server? Because if so, I don't own the server I'm using on PKC... but if that's a necessary step for me to get these exact debug infos, I can connect my own server on PKC! I'm saying that because Plex is just NOT writing anything on transcoding using PKC.

**Comment by SuperPepperoni** [comment]
* I'm struggling with your PMS logs.
And just to explain where I got that "[PMS Debug Log](https://gist.github.com/SuperPepperoni/05f16254375112fe777544770401f3a9)": I went to Plex's Settings > Debug > Debug Level: "Enabled" and sent you the debug logs.

**Comment by croneter** [comment]
Yes, guess you need to own the PMS 😆. Theoretically, the owner could cut down on the possible transcoding quality settings. I need to see the PMS logs to see what's going on. On my personal PMS, everything is working fine now.

**Comment by SuperPepperoni** [comment]
Then I'm gonna hard reset PKC and set it up with my own server to see if the fix works, will be back soon.

**Comment by SuperPepperoni** [comment]
Just set up PKC to my server and good news... I guess I can call it good news? The transcoding bug is also happening locally, lmao.
Now, I say good news because (1) now we know this bug is very likely related to my side of things (2) the log finally gave us strings on the matter!

In this case, I tried to transcode a 1080p "Mulholland Drive" to 720p/4Mbps. The playback quality was reduced to a 720x390. I think all the requests related to the transcode are called "Req#7e5": [Here it is.](https://gist.githubusercontent.com/SuperPepperoni/11aba9826cc921f4fcc420b69ed1b643/raw/56a4a3a1c58a2c037213b7edceaaaf1c7a21be17/Plex-MyServer-Log)

**Comment by SuperPepperoni** [comment]
Found this string and I think it's most definitely related to what we're looking for:

``Nov 11, 2024 13:45:56.607 [8988] DEBUG - [Req#7e5/Transcode] Streaming Resource: Required bandwidth unknown (media requires deep analysis) Changing decision parameters provided by client to fit bandwidth limit of 2000kbps``

Edit: Why do I feel like this is something related to port forwarding? I'm gonna have a look at it while you're out...

**Comment by SuperPepperoni** [comment]
So, I think this has something to do with Plex's Remote Access settings.
Ever since I changed internet providers, I haven't managed to activate the router's Port Forward settings.
Tried to do it now, but it just **Won't Work**, thus I can't activate Remote Access.

I'm gonna wait for you to have a look at the log and see if you reach any conclusion... But I have a feeling that I need to activate Remote Access, because I think I'll be able to adjust the "Internet Upload Speed" setting when it activates:

![Screen-Shot-2021-02-27-at-12 24 45-PM-1024x655](https://github.com/user-attachments/assets/12e664e8-6008-4f14-8096-771f4ec1462b)

Thus, informing Plex the ``unknown `` ``Required bandwidth`` from the log. I don't know, that's the best bet I have, but I'm not even sure if this setting still exists. Can you see this "Internet Upload Speed" in your PMS?

**Comment by croneter** [comment]
Thanks for your research!! 

There you have it, unfortunately: `Limit remote stream bitrate` set to `4 Mbps (720p)`. That's the max quality the PMS will accept when transcoding. On my PMS, I did not set a limit, hence this "bug" was not manifesting for my set-up.

**Comment by SuperPepperoni** [comment]
Yeah, but I got this screenshot from Google because I can't see how mine looks now, so what I'm gonna do is: I'm gonna deal with my port forwarding issue ASAP, activate Remote Access on my PMS, test to check if this is it and return to close this issue once and for all!!

I'll be back. 🧘‍♂️

**Comment by croneter** [comment]
Closing for now
