### ISSUE TITLE
File always starts from the beginnig / Kodi 18 Alpha 3

### ISSUE THREAD

**Issue by destriktion** [croneter/PlexKodiConnect#525]
Hi, everybody,

I have the following problem. If I want to continue looking for a started title, it always starts from the beginning and not from the last completed position.
I’m using Kodi 18 Alpha 3 and the latest plexkodiconnect beta version.

**Comment by trenst** [comment]
I have the same problem.  I updated 2 computers to Kodi 18 Alpha 3.  plexkodiconnect had no problem resuming from the last stopped position before I updated. 
 Now, it always restarts the video on both computers.  My playback mode is Direct Play.  Version 2.3.8 of plexkodiconnect is installed.

**Comment by joonon** [comment]
Kodi 18 Alpha 3 with 2.3.8 of PKC with the same issue, running on a Nvidia Shield TV.

**Comment by caphm** [comment]
@destriktion you did not follow [How-to-Report-A-Bug](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug) and published your plex token. Please follow [I published my Plex token to some forum or Github. Anyone can now access my Plex Server!](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server) to secure your plex server.

**Comment by destriktion** [comment]
I thought I had deleted all tokens.
Then please create a log file.

**Comment by croneter** [comment]
@destriktion Darn I did not download your log file yet. Could you please post again without the tokens?

Thanks @caphm for noticing!

**Comment by destriktion** [comment]
Second try: 
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2299605/kodi.log)

**Comment by trenst** [comment]
Here's my log file as well.
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2299756/kodi.log)

**Comment by trenst** [comment]
Just FYI...  I have no problem resuming video from other sources like Amazon prime video.

**Comment by croneter** [comment]
Should be solved. Kodi 18 broke the `StartOffset` property for Kodi ListItems, thanks very much

**Comment by redstar92** [comment]
tried this yesterday on Xbox One and was still seeing it.  Should I try again later today?

**Comment by croneter** [comment]
Just updated 1 hour ago - so try again, making sure your using beta version 2.3.9

**Comment by dobbleg1000** [comment]
I seem to be having this issue with version 2.9.3 and beta version 2.9.4 on kodi 18.3

**Comment by croneter** [comment]
@dobbleg1000 
Works perfectly fine here. Please share a DEBUG log of you duplicating the issue: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by dobbleg1000** [comment]
https://pastebin.com/UURPtgmX
