### ISSUE TITLE
Kodi 18 Leia: Music Library wants to rescan tags every time

### ISSUE THREAD

**Issue by metzger2309** [croneter/PlexKodiConnect#527]
Hi ! Since I updated PKC to 2.3.8, each time I want to open the music Library, PKC wants to update and rescan the tags. But nothing happans...  I already deleted all libraries, but its comming again and again... Any idea?

**Comment by croneter** [comment]
Not without a log: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by metzger2309** [comment]
sure, just tried it. hope its working...

https://pastebin.com/tVs8eWAx

**Comment by croneter** [comment]
I can't see anything suspicious in your log file. What do you mean with `PKC wants to update and rescan the tags`? What tags? Could you make a screenshot, maybe?

**Comment by dazedcrazy** [comment]
Everytime you go into music you get this dialog
![2irkiho](https://user-images.githubusercontent.com/9027988/44523714-c6981a00-a6d2-11e8-8d13-d2acbae3792b.png)
I assume that's what he means, i rarely go into music as i play stuff from playlists but when i do i get that dialog popup

**Comment by croneter** [comment]
Does it help if you deactivate `Enable tag reading`, then restart Kodi?
![image](https://user-images.githubusercontent.com/4637940/44528753-95c3df00-a6ea-11e8-910e-37dda0a61fdc.png)

**Comment by croneter** [comment]
Also, is this only an issue with Kodi 18 Leia oder also for 17.6 Krypton?

**Comment by dazedcrazy** [comment]
> Does it help if you deactivate Enable tag reading in the Kodi Media settings, then restart Kodi?

Doesn't help

> Also, is this only an issue with Kodi 18 Leia oder also for 17.6 Krypton?

Doesn't happen with 17.6

**Comment by croneter** [comment]
The obvious solution is to use STABLE Kodi 17.6 Krypton :wink:. Issues like this one are bound to still happen with Kodi 18

**Comment by metzger2309** [comment]
yes dazedcrazy was right, this was the fault I meant... thats a pitty there is no solution. Maybe it will solve in a further version if kodi 18 from alone.

**Comment by croneter** [comment]
I could not reproduce this bug using the newest Kodi Leia Beta 3. Issue solved?

**Comment by dazedcrazy** [comment]
> 
> 
> I could not reproduce this bug using the newest Kodi Leia Beta 3. Issue solved?

No it's still an issue

**Comment by dazedcrazy** [comment]
Log: 
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2454010/kodi.log)

Could this be causing it
PKC db
![image](https://user-images.githubusercontent.com/9027988/46583059-b81a7d80-ca48-11e8-8f46-77f19342d4af.png)
Standard Kodi db
![image](https://user-images.githubusercontent.com/9027988/46583061-c2d51280-ca48-11e8-8355-1bd2de7532de.png)
Similar to how the genre not starting at 1?

**Comment by croneter** [comment]
Thanks for the info @dazedcrazy . Please try the new beta version 2.4.6 and let me know

By the way: a PKC database reset does not help? (PKC settings, Advanced, then Reset the Kodi database, then YES, NO)

**Comment by dazedcrazy** [comment]
After a reset it doesn't happen the first time you enter music but then after a restart of kodi it happens. I'll reset db and test new beta now

**Comment by croneter** [comment]
What program are you using to view the database? I use python but it's a bit of a pain

**Comment by dazedcrazy** [comment]
https://sqlitebrowser.org/ it's free

**Comment by croneter** [comment]
Really really helpful, by the way, thanks so much!

**Comment by dazedcrazy** [comment]
https://github.com/xbmc/xbmc/pull/11557 that's the PR i think that added the versiontagscan

**Comment by croneter** [comment]
Fixed in 2.4.7. You will need to **manually** reset the database in the PKC Settings under Advanced, though. I did not want to force everyone to reset 😉

**Comment by disrupted** [comment]
I am on 2.4.9 and still seeing this issue after doing a full Kodi database reset. might try the manual route with editing the SQLite DB tomorrow.

**Comment by benkap** [comment]
I can confirm the same issue with 18 rc4 with emby addon. Happen even when emby doesn't manage the music library and after full kodi db reset. Music files are on NFS share (kodi running on linux lite)
