### ISSUE TITLE
Cannot use Plex default subtitle settings

### ISSUE THREAD

**Issue by loeffelpan** [croneter/PlexKodiConnect#594]
In the options of your addon is a checkbox to enable plex default subtitle.
Unfortunately I can't get any different behaviourv by activating this.
In your Plex forum thread the only hint is, that Kodi controls subtitle selecting with its own settings.

Can you explain what the above mentioned option does?
And how to configure Kodi to reach that it displays the subtitle selected on PMS by default?
I though that option is to achieve exactly this.

Thanks,
Jan

**Comment by spamies1** [comment]
[https://forums.plex.tv/t/plexkodiconnect-kodi-plex-integration-done-right/137555/4281?u=spamies](url)

> If you’re using PKC Add-on Paths, PKC should tell Kodi to automatically show the “correct” subtitle Plex suggests (due to your PMS settings).
If Plex subtitles are missing, that’s because PKC cannot just grab them and make them available for Kodi. You can still access them by using the Kodi context menu on the video, then choose Force Transcode. You’ll be prompted to select a subtitle. The ones not being “natively” available to Kodi will show up with the additional text “burn-in” - because the PMS will have to burn them in while transcoding.

So if you are using PKC add-on paths then plex subtitles should work. I assume you are using direct paths like me and don't see plex default subtitles. If you are using direct paths PKC cannot grab the subtitles from plex and will only show them if you force transcoding and have plex burn-in the subtitles. I would suggest using kodi plugin auto subs instead of transcoding.

[https://kodi.wiki/view/Add-on:AutoSubs](url)

**Comment by coz2001** [comment]
I use direct paths and never had any problems with subtitles they always show with the language I have set in PMS settings, so not sure what's the issue is.

**Comment by loeffelpan** [comment]
@spamies1 Thanks for advise. I‘ll give it a try with Add-on Paths or an addon for kodi to select subs.
@coz2001 Could please you provide more detail about your setup? Kodi selects subtitles for me if I tell in kodis settings. But this has nothing to do with autoselection of subtitles in PMS, I think.

**Comment by croneter** [comment]
The setting does exactly that **with PKC direct paths enabled only** (or if you choose "Start playback via PMS" from the Kodi context menu)

**Comment by croneter** [comment]
There is no way for Kodi to use the Plex subtitle settings otherwise.

**Comment by loeffelpan** [comment]
Didn‘t you mean „With Addon Path only“?
That‘s what I expect will happen when choosing „Start playback via PMS“ with Direct Path configured.

**Comment by loeffelpan** [comment]
Can't get this to work.
Neither with Addon Path nor with Direct Path. My subtitles are streams inside mkv files.

I set Kodi to select no subtitles and hit the option in Plex setting to use default subtitle. But no subtitles will appear by clicking "Start playback with via PMS" (with direct path) or while playback via addon path.

Manually selecting them by kodi's menu works fine.
Forcing to transcode and select a subtitle will work obviously, too.

Where is my fault?

**Comment by loeffelpan** [comment]
Anything new here?

**Comment by loeffelpan** [comment]
Seems to be fixed with 2.6.4 from official repo.

**Comment by croneter** [comment]
Eeeehm - I didn't do anything :laughing:. Working now for you, @loeffelpan ? Did you change some setting?

**Comment by loeffelpan** [comment]
Yeah. I didn't change a setting. I set up a new instance of Kodi on my iPad. To be sure that the subtitle association doesn't come from Kodi, I reset the database.

I will check that on my RasPi soon.

**Comment by croneter** [comment]
I guess this is fixed

**Comment by loeffelpan** [comment]
Just tested this again.
Unfortunately it‘s not fixed as I thought. I had a fresh instance of Kodi with a setting that Kodi selects subtitle. Could you please check that again?

Just to be sure not to have an user failure:
How should this work? I guess I have to set Kodis subtitle to „deactivate“, check the box in PKC settings and use addon-path. Right?

**Comment by williamvw** [comment]
I am using all the recommend settings to play ota channels with Hdhomerun and Nvidia Shield with Kodi Leia.   While I play a video (direct play) in Kodi from the PKC folder,  I click on settings icon and enable subtitles   and also save the settings.    The embedded subtitles work,  but every time I go back into same video or other Plex recordings in Kodi,   I have to enable all over again.   The settings do remain enabled for other sources such as my kodi sideloaded Netflix.   Using PKC addon path and PKC subtitle setting is turned on.   How can I get the subtitles  to "stick" for  Plex sourced videos?

**Comment by davidfrickert** [comment]
Was having this problem as well.
No external subtitles were loading - only those embedded in the file were.
So it seems that if you go to settings and then 'Playback' section and change from 'Direct Play' to 'Direct Stream', external subtitles do appear.

@croneter can you perhaps take a look at this?

**Comment by JoshBeer** [comment]
I have the exact same problem. External subtitles don't get recognized but embedded subtitles are.
I hope there is a fix to this because I actually do have many external subtitles I'd like to use.
Other than that I LOVE PKC. But I had to use Plex for Kodi every now and then if I want to use external subtitles.

**Comment by kat953162** [comment]
@croneter So what is the progress on this issue? I generally use Direct Paths but would be willing to switch to Addon if it were to properly show the right subtitles based on my Plex settings. I attempted changing all sorts of settings across Kodi and Plex, and in different combinations, couldn't get it to work.

**Comment by croneter** [comment]
Should finally be solved with PKC 3.4.3
