### ISSUE TITLE
[Direct Path] Playing from Newly Added isn't reported to plex

### ISSUE THREAD

**Issue by Inervo** [croneter/PlexKodiConnect#766]
## Describe the bug
Configuration:
Kodi 18.1
PKC 2.5.4, Direct Path

In Kodi, when playing a TV show episode from the "newly added" (**directly from the main page**), Plex isn't reporting anything regarding a video being watched. Thus, not synchronizing the progress if the video is stopped in the middle of the episode.
However, if i go in ANY sub-menu (like "in progress" submenu, or any other), and i play it from there, Plex is showing a video is being watched perfectly.

Am I doing something wrong, or is this a bug?

Here is the debug log:
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2971141/kodi.log)
Tried to played the episode from kodi twice:
- first time, from the main kodi tv show screen --> no sync with plex
- second time from TV show page --> sync with plex

**Comment by croneter** [comment]
Should be solved with stable and beta version 2.7.7. Let me know here if this is not the case.

**Comment by Inervo** [comment]
Hi,

It's seems that the issue still exists.

PKC 2.7.9

Exactly the same problem

Here is the debug log:
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/3014724/kodi.log)
Once again, played the episode from kodi twice:
- first time, from the main kodi tv show screen --> no sync with plex
- second time from TV show page --> sync with plex

**Comment by croneter** [comment]
Should be solved with PKC stable and beta version 2.7.10. Let me know here if this is not the case
