### ISSUE TITLE
Newly added movie file appeared on Plex but didn't on Kodi

### ISSUE THREAD

**Issue by C-Duv** [croneter/PlexKodiConnect#90]
After adding a file into my movies' Plex library, it appeared on Plex web interface but didn't on Kodi (v17, running PKC v1.2.11), event after 5 minutes.
I played the movie via the Plex web interface, and _seeked_ for it to appear as "In progress" on the web interface. But it still didn't show up on Kodi.
Manually running a library update via the button on Kodi "Movies" main view (I'm using default skin _Estuary_) does not seems to do anything: status area (where the date and time is typically displayed) do disappear for a second but that's about it.

I did a "library refresh", which did triggered some synchronization from PKC, but still no new movie...

Note that I restarted Kodi between each tests.

Looks like #23, except it's for movies.

**Comment by croneter** [comment]
Restarting Kodi didn't help? You can't find the new item at all, even if searching for it?

Logs please ;-) https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by C-Duv** [comment]
I have looked into every menu and cannot find the new movie.

`Kodi.log` indicates that the movie (named _FoobarMovieTitle_) is somehow advertised to PKC be cause it appears in it.

Here are the interesting lines:
```
19:52:51 T:18446744071774679936  NOTICE: PlexKodiConnect LibrarySync -> maintainViews : Removing views: []
19:52:51 T:18446744071774679936  NOTICE: PlexKodiConnect LibrarySync -> maintainViews : Finished processing views. Views saved: [{'itemtype': u'movie', 'id': u'5', 'name': u'Documentaires'}, {'itemtype': u'movie', 'id': u'1', 'name': u'Films'}, {'itemtype': u'show', 'id': u'2', 'name': u'S\xe9ries TV'}]
19:52:51 T:18446744071774679936  NOTICE: PlexKodiConnect LibrarySync -> PlexMovies : Processing Plex Movies. Libraries: [{'itemtype': u'movie', 'id': u'5', 'name': u'Documentaires'}, {'itemtype': u'movie', 'id': u'1', 'name': u'Films'}]
19:52:54 T:18446744071774679936  NOTICE: PlexKodiConnect LibrarySync -> GetAndProcessXMLs : self.updatelist: [..., {'itemId': '7639', 'itemType': 'Movies', 'viewName': u'Films', 'title': 'FoobarMovieTitle', 'viewId': u'1', 'method': 'add_update'}, ...]
19:52:54 T:18446744071774679936  NOTICE: PlexKodiConnect LibrarySync -> GetAndProcessXMLs : Starting sync threads
19:52:54 T:18446744071774679936  NOTICE: PlexKodiConnect LibrarySync -> GetAndProcessXMLs : 5 download threads spawned
19:52:54 T:18446744071774679936  NOTICE: PlexKodiConnect LibrarySync -> GetAndProcessXMLs : Processing thread spawned
19:52:54 T:18446744071775170816  NOTICE: Using Image Cache Thread Count: 25 -> __init__ : 1
19:52:54 T:18446744071774679936  NOTICE: PlexKodiConnect LibrarySync -> GetAndProcessXMLs : Kodi Infobox thread spawned
19:52:54 T:18446744071887197824  NOTICE: VideoInfoScanner: Starting scan ..
19:52:54 T:18446744071887197824  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00
19:52:54 T:18446744071877029504  NOTICE: PlexKodiConnect KodiMonitor -> onScanStarted : Kodi library scan video running.
19:52:54 T:18446744071877029504  NOTICE: PlexKodiConnect KodiMonitor -> onNotification : Method: VideoLibrary.OnScanStarted Data: null
19:52:54 T:18446744071877029504  NOTICE: PlexKodiConnect KodiMonitor -> onScanFinished : Kodi library scan video finished.
19:52:54 T:18446744071877029504  NOTICE: PlexKodiConnect KodiMonitor -> onNotification : Method: VideoLibrary.OnScanFinished Data: null
19:52:54 T:18446744071775170816  NOTICE: Using Image Cache Thread Count: 25 -> __init__ : 1
[...]
19:53:01 T:18446744071774673536  NOTICE: PlexKodiConnect WebSocket -> process : Received message from PMS server: {u'_elementType': u'NotificationContainer', u'_children': [{u'itemID': 7639, u'title': 'FoobarMovieTitle', u'sectionID': 1, u'_elementType': u'TimelineEntry', u'state': 5, u'updatedAt': 1470851581, u'queueSize': 3, u'type': 1, u'metadataState': u'processing'}], u'type': u'timeline', u'size': 1}
[...]
19:53:02 T:18446744071774673536  NOTICE: PlexKodiConnect WebSocket -> process : Received message from PMS server: {u'_elementType': u'NotificationContainer', u'_children': [{u'itemID': 7639, u'title': 'FoobarMovieTitle', u'sectionID': 1, u'_elementType': u'TimelineEntry', u'state': 4, u'updatedAt': 1470851582, u'queueSize': 3, u'type': 1, u'metadataState': u'loading'}], u'type': u'timeline', u'size': 1}
[...]
19:53:03 T:18446744071774673536  NOTICE: PlexKodiConnect WebSocket -> process : Received message from PMS server: {u'_elementType': u'NotificationContainer', u'_children': [{u'itemID': 7639, u'title': 'FoobarMovieTitle': 1, u'_elementType': u'TimelineEntry', u'state': 5, u'updatedAt': 1470851582, u'queueSize': 3, u'type': 1}], u'type': u'timeline', u'size': 1}
[...]
19:53:44 T:18446744071775170816  NOTICE: PlexKodiConnect Kodidb_Functions -> addTags : Adding Tags: [u'Films']
19:53:44 T:18446744071775170816  NOTICE: PlexKodiConnect Items -> run_add_update : UPDATE movie itemid: 7639 - Title: FoobarMovieTitle
19:53:44 T:18446744071742174080  NOTICE: PlexKodiConnect image_cache_thread -> run : Image Caching Thread Exited
19:53:45 T:18446744071775170816  NOTICE: Previous line repeats 3 times.
[...]
19:53:45 T:18446744071775170816  NOTICE: PlexKodiConnect API -> getExternalItemId : Start movie set/collection lookup on themoviedb
19:53:45 T:18446744071742169600  NOTICE: PlexKodiConnect image_cache_thread -> run : Image Caching Thread Exited
19:53:46 T:18446744071775170816  NOTICE: PlexKodiConnect API -> getExternalItemId : Found themoviedb match for FoobarMovieTitle: {u'poster_path': u'/cGOP.jpg', u'title': 'FoobarMovieTitle', u'overview': '....', u'release_date': u'...', u'popularity': 24.42, u'original_title': 'FoobarMovieTitle', u'backdrop_path': u'/vsjBeMPZtQZ.jpg', u'vote_count': 42, u'video': False, u'adult': False, u'vote_average': 5, u'original_language': u'en', u'id': 208351, u'genre_ids': [28, 12, 14]}
19:53:46 T:18446744071775170816  NOTICE: PlexKodiConnect API -> getExternalItemId : Retrieved collections tmdb id 999
19:53:46 T:18446744071810660992  NOTICE: PlexKodiConnect image_cache_thread -> run : Image Caching Thread Exited
19:53:46 T:18446744071775170816  NOTICE: Previous line repeats 1 times.
[...]
19:58:29 T:18446744071774679936  NOTICE: PlexKodiConnect LibrarySync -> process_newitems : Processing new/updated PMS item: 7639
19:58:29 T:18446744071774679936  NOTICE: Using Image Cache Thread Count: 25 -> __init__ : 1
19:58:29 T:18446744071774679936  NOTICE: Previous line repeats 1 times.
19:58:29 T:18446744071774679936  NOTICE: PlexKodiConnect Items -> run_add_update : UPDATE movie itemid: 7639 - Title: FoobarMovieTitle
19:58:30 T:18446744071774679936  NOTICE: PlexKodiConnect Kodidb_Functions -> addTags : Adding Tags: ['Films', 'DC Heroes']
19:58:30 T:18446744071774679936  NOTICE: PlexKodiConnect Kodidb_Functions -> createBoxset : Adding boxset: DC Heroes
19:58:30 T:18446744071774679936  NOTICE: PlexKodiConnect API -> getExternalItemId : Start movie set/collection lookup on themoviedb
19:58:30 T:18446744071775164416  NOTICE: PlexKodiConnect image_cache_thread -> run : Image Caching Thread Exited
19:58:30 T:18446744071774679936  NOTICE: Previous line repeats 1 times.
19:58:30 T:18446744071774679936  NOTICE: PlexKodiConnect API -> getExternalItemId : Found themoviedb match for FoobarMovieTitle: {u'poster_path': u'/cGOP.jpg', u'title': 'FoobarMovieTitle', u'overview': '....', u'release_date': u'...', u'popularity': 24.42, u'original_title': 'FoobarMovieTitle', u'backdrop_path': u'/vsjBeMPZtQZ.jpg', u'vote_count': 42, u'video': False, u'adult': False, u'vote_average': 5, u'original_language': u'en', u'id': 208351, u'genre_ids': [28, 12, 14]}
```

**Comment by croneter** [comment]
Well, that's odd, the movie was processed just fine. It's part of a [movie set](http://kodi.wiki/view/movie_sets) called `DC Heroes`, can you find it in there? If not, have you tried resetting the PKC database in the PKC settings under advanced?

**Comment by croneter** [comment]
Issue solved?

**Comment by croneter** [comment]
Guess this issue is solved, let me know if not

**Comment by C-Duv** [comment]
A full database reset didn't helped: the missing movies' name did appeared in the status bar during synchronization but was still missing from movie home-screen and list.

I have fully uninstalled Kodi (v17 alpha) and re-installed it. And this time I installed PlexKodiConnect v1.2.14 (beta repository).

My missing movies (the one added after my first PKC installation) appeared just fine: which is pretty normal.
And now, I have just tested to add a new movie to my Plex server: it did appeared on the movie home-screen!

So either fully re-installing Kodi or using v1.2.14 (instead of v1.2.10) fixed the bug.
